# Exercise 1

1.
```{r}
# Input X: matrix
kmeanspp <- function(x, k) {
  x_row <- nrow(x)
  
  center_index <- sample(1:x_row, size=1)
  
  for (i in 2:k) {
    D <- c()
    for (d in 1:x_row) {
      data_centers_distances <- c()
      for (c in center_index) {
        data_centers_distances <- c(data_centers_distances, sum((x[d,]-x[c,])^2))
      }
      D <- c(D, min(data_centers_distances))
    }
    center_index <- c(center_index, which.max(D^2/sum(D^2)))
  }
  
  return(kmeans(x, centers=x[center_index,]))
}
```

2.
```{r}
NORM <- function(n) {
  set.seed(NULL)
  dim <- 15
  center_coor <- c()
  for (i in 1:(n*dim)) {
    center_coor <- c(center_coor, runif(1, min=0, max=500))
  }
  true_centers <- matrix(center_coor, nrow=n, ncol=dim, byrow=TRUE)
  
  res <- c()
  for (ct_row in 1:n) {
    for (i in 1:400) {
      for (ct_col in 1:dim) {
        res <- c(res, rnorm(1, mean=true_centers[ct_row, ct_col], sd=1))
      }
    }
  }
  return(matrix(res, ncol=dim, byrow=TRUE))
}
```


# Exercise 2

1.
```{r}
data_iris <- iris[,1:4]
```

```{r}
k1 <- kmeans(data_iris, centers=2)
```

```{r}
library(mclust)
m <- Mclust(data_iris)
plot(m, "BIC")
```