```{r}
d <- read.table("neighbor_globin.txt", header=FALSE, row.names=1)
colnames(d) <- rownames(d)
```

```{r}
# Verify that d = d^T
sum((d-t(d))^2)
```

```{r}
h <- hclust(as.dist(d))
plot(h)
```

```{r}
afp <- cmdscale(as.matrix(d), k=4, eig=TRUE)
pch.type <- c(rep(1,6), rep(2,7), rep(3,7), 4)
colors <- c(1:6, 4, 7, 8, 1:3, 5, 4, 7, 5, 1:3, 8, 9)
plot(afp$points, pch=pch.type, col=rainbow(9)[colors])
legend("topleft", legend=c("Myoglobin", "Hemoglobin Beta", "Hemoglobin Alpha", "Globin-3"), pch=1:4)
```

```{r}
sh <- Shepard(as.dist(d), afp$points)
str(sh)
plot(sh)
```

```{r}
d <- as.matrix(d)
n <- nrow(d)
J <- diag(rep(1,n)) - 1/n * matrix(1,n,n)
(J %*% d^2 %*% J * (-1/2)) -> M
q <- 2
eigen(M) -> PCoA
vp <- PCoA$values[1:q]
Ctilde <- PCoA$vectors[, 1:q]
C <- Ctilde %*% diag(sqrt(vp))
```

Pour $q=n$
$$\frac{\text{cumsum}(vp)}{\text{sum}(vp)}$$
où $\text{sum}(vp)$ est l'inertie totale.

```{r}
plot(afp$eig)
abline(b=0, "red")
sum(afp$eig<0)
cumsum(afp$eig) / sum(afp$eig)
plot(cumsum(afp$eig) / sum(afp$eig))
```

$$\text{Stress} = \frac{1}{n} \sum_{i>j}(d(i,j)-||c_i-c_j||)^2$$
where $d(i,j)$ is the dissimilarity in the space of origin and
$||c_i-c_j||$ is the distance in the constructed space.



ACP:
$$\frac{I_{E^\perp}}{I_T} = \frac{||X - \tilde{X}||_2^2}{||X||_2^2}, \text{ where } \tilde{X} = \sum_{j=1}^{q}c^ju^Tj$$
